[project]
name = "synth-streamlines"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dipy>=1.10.0",
    "fury>=0.12.0",
    "ipympl>=0.9.6",
    "matplotlib>=3.10.0",
    "nibabel>=5.3.2",
    "nipype>=1.9.2",
    "numpy>=2.2.2",
    "persim>=0.3.7",
    "pyqt6>=6.8.1",
    "pyvista>=0.44.2",
    "ripser>=0.6.10",
    "scipy>=1.15.2",
]
